---
title: "stateSpaceModExample"
author: "Sara Stoudt"
date: "September 16, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("MCMCmaxlik")
```


```{r,eval=F}
#ssModel$rho <- 0.5
#ssModel$mu <- 5.0
#ssModel$sigPN <- 5
#ssModel$sigOE <- 5

set.seed(931154)
rho=0.5
sigPN=5
sigOE=5
x0=5
TT=100
x=rep(rnorm(1,rho*x0,sd=sqrt(sigPN^2/(1-rho*rho))),TT)
y=rep(rnorm(1,x[1],sd=sigOE),TT)
for(i in 2:TT){
  x[i] =rnorm(1,rho * x[i - 1] , sd = sigPN)
    y[i] =rnorm(1,x[i], sd = sigOE)
}
```

```{r,eval=F}
ssCode <- nimbleCode({
  rho ~ dunif(-0.9999, 0.9999)
  #mu ~ dnorm(0, sd = 1000) # 0
  sigPN ~ dunif(1e-04, 100)
  sigOE ~ dunif(1e-04, 100)
  x0 ~dnorm(0, sd = 1000)
  x[1] ~ dnorm(rho*x0, sd = sqrt(sigPN^2/(1-rho*rho)))
  #x[1] ~ dnorm(rho*x0, sd = sigPN)
  #x[1] ~ dnorm(mu, sd = sqrt(sigPN^2/(1-rho*rho)))
  y[1] ~ dnorm(x[1], sd = sigOE)
  for (i in 2:TT) {
    #x[i] ~ dnorm(rho * (x[i - 1] - mu) + mu, sd = sigPN)
    x[i] ~ dnorm(rho * x[i - 1] , sd = sigPN)
    y[i] ~ dnorm(x[i], sd = sigOE)
  }
}) ## take out mu

Consts <- list(TT = 100)

data <- list(
  x=x,
  y=y
)


## build the model object
ssModel <- nimbleModel(ssCode, constants = Consts,data=data)

## put values in the top-level parameters
#ssModel$rho <- 0.5
#ssModel$mu <- 5.0
#ssModel$sigPN <- 5
#ssModel$sigOE <- 5

## calculate any dependencies that may be needed to simulate states and data
#ssModel$calculate(ssModel$getDependencies( c('rho','sigPN','sigOE'), determOnly = TRUE))


## use the model to simulate states and data
#set.seed(12345)
#ssModel$simulate( ssModel$getDependencies(c('x','y')))
## Look at what we got:
#ssModel$x
#ssModel$y
#ssModel$setData('y')

write.csv(cbind(x,y),"statespaceModData.csv")

paramNodesSS <- ssModel$getNodeNames(topOnly=T)
CssModel <- compileNimble(ssModel)
```


```{r,cache=T}
set.seed(931154)
rho=0.5
sigPN=5
sigOE=5
x0=5
TT=100
x=rep(rnorm(1,rho*x0,sd=sqrt(sigPN^2/(1-rho*rho))),TT)
y=rep(rnorm(1,x[1],sd=sigOE),TT)
for(i in 2:TT){
  x[i] =rnorm(1,rho * x[i - 1] , sd = sigPN)
    y[i] =rnorm(1,x[i], sd = sigOE)
}

ssCode <- nimbleCode({
  rho ~ dunif(-0.9999, 0.9999)
  #mu ~ dnorm(0, sd = 1000) # 0
  sigPN ~ dunif(1e-04, 100)
  sigOE ~ dunif(1e-04, 100)
  x0 ~dnorm(0, sd = 1000)
  x[1] ~ dnorm(rho*x0, sd = sqrt(sigPN^2/(1-rho*rho)))
  #x[1] ~ dnorm(rho*x0, sd = sigPN)
  #x[1] ~ dnorm(mu, sd = sqrt(sigPN^2/(1-rho*rho)))
  y[1] ~ dnorm(x[1], sd = sigOE)
  for (i in 2:TT) {
    #x[i] ~ dnorm(rho * (x[i - 1] - mu) + mu, sd = sigPN)
    x[i] ~ dnorm(rho * x[i - 1] , sd = sigPN)
    y[i] ~ dnorm(x[i], sd = sigOE)
  }
}) ## take out mu

Consts <- list(TT = 100)

ssModel <- nimbleModel(ssCode, constants = Consts)

## put values in the top-level parameters
ssModel$rho <- 0.5
ssModel$x0 <- 5.0
ssModel$sigPN <- 5
ssModel$sigOE <- 5

## calculate any dependencies that may be needed to simulate states and data
ssModel$calculate(ssModel$getDependencies( c('rho','x0','sigPN','sigOE'), determOnly = TRUE))


## use the model to simulate states and data
set.seed(12345)
ssModel$simulate( ssModel$getDependencies(c('x','y')))
## Look at what we got:
ssModel$x
ssModel$y
ssModel$setData('y')


write.csv(cbind(ssModel$x,ssModel$y),"statespaceModData.csv")

paramNodesSS <- ssModel$getNodeNames(topOnly=T)
CssModel <- compileNimble(ssModel)


```


```{r compile}
compiledFunsSSmodel <- buildMCMCmaxlik(ssModel, paramNodesSS)
```


# Testing Algorithms

```{r}
# 1. Fixed step size ----------------------------------------
# Compile the necessary functions.

init <- c(0.75,10,10,10)
boundary <- list(c(-0.9999, 0.9999),c(1e-04, 100),c(1e-04, 100),c(-100000,100000))
numMCMCSamples <- 300

ptm <- proc.time()
resultsSSModFixed <- computeMLE(ssModel, paramNodesSS,
                               method="fixed", paramInit=init,
                               compiledFuns=compiledFunsSSmodel,
                               stepsize=0.05,
                               numMCMCSamples=numMCMCSamples,
                               maxIter=300,
                               boundary=boundary,trackEffSizeGrad=F,skipConvCheck=T)
timeSSModFixed <- proc.time() - ptm
timeSSModFixed  ## 17.573 
resultsSSModFixed$iter ## 300
mean(tail(resultsSSModFixed$param[, 1], 20), trim=.2)  #  0.5076828
mean(tail(resultsSSModFixed$param[, 2], 20), trim=.2)   # 4.086307
mean(tail(resultsSSModFixed$param[, 3], 20), trim=.2) #  6.391043
mean(tail(resultsSSModFixed$param[, 4], 20), trim=.2)  # 10.14549

save(resultsSSModFixed, file="SSModFixed.RData")

ptm <- proc.time()
resultsSSModFixed2 <- computeMLE(ssModel, paramNodesSS,
                               method="fixed", paramInit=init,
                               compiledFuns=compiledFunsSSmodel,
                               stepsize=0.05,
                               numMCMCSamples=numMCMCSamples,
                               maxIter=300,
                               boundary=boundary,trackEffSizeGrad=F,skipConvCheck=F)
timeSSModFixed2 <- proc.time() - ptm
timeSSModFixed2  ## 19.158 
resultsSSModFixed2$iter ## 300
mean(tail(resultsSSModFixed2$param[, 1], 20), trim=.2)  # 0.5417394
mean(tail(resultsSSModFixed2$param[, 2], 20), trim=.2)   # 3.902005
mean(tail(resultsSSModFixed2$param[, 3], 20), trim=.2) # 6.459115
mean(tail(resultsSSModFixed2$param[, 4], 20), trim=.2)  # 10.1137

save(resultsSSModFixed2, file="SSModFixedCC.RData")
```

```{r}
# 2. Small fixed step size ----------------------------------------
ptm <- proc.time()
resultsSSModSmallFixed <- computeMLE(ssModel,paramNodesSS,
                                    method="fixed", paramInit=init,
                                    compiledFuns=compiledFunsSSmodel,
                                    stepsize=0.005,
                                    numMCMCSamples=numMCMCSamples,
                                    maxIter=3000,
                                    boundary=boundary,trackEffSizeGrad=F,skipConvCheck=T)
timeSSModSmallFixed <- proc.time() - ptm
timeSSModSmallFixed  ##186.640 
resultsSSModSmallFixed$iter ## 3000
mean(tail(resultsSSModSmallFixed$param[, 1], 20), trim=.2)  ## 0.5219547
mean(tail(resultsSSModSmallFixed$param[, 2], 20), trim=.2) ## 4.650584
mean(tail(resultsSSModSmallFixed$param[, 3], 20), trim=.2)  ##  5.891227
mean(tail(resultsSSModSmallFixed$param[, 4], 20), trim=.2) ## 10.35237
save(resultsSSModSmallFixed, file="SSModSmallFixed3000.RData")

ptm <- proc.time()
resultsSSModSmallFixed2 <- computeMLE(ssModel,paramNodesSS,
                                    method="fixed", paramInit=init,
                                    compiledFuns=compiledFunsSSmodel,
                                    stepsize=0.005,
                                    numMCMCSamples=numMCMCSamples,
                                    maxIter=3000,
                                    boundary=boundary,trackEffSizeGrad=F,skipConvCheck=F)
timeSSModSmallFixed2 <- proc.time() - ptm
timeSSModSmallFixed2  ##179.970 
resultsSSModSmallFixed2$iter ## 3000
mean(tail(resultsSSModSmallFixed2$param[, 1], 20), trim=.2)  ## 0.5189702
mean(tail(resultsSSModSmallFixed2$param[, 2], 20), trim=.2) ## 4.675914
mean(tail(resultsSSModSmallFixed2$param[, 3], 20), trim=.2)  ##   5.881506
mean(tail(resultsSSModSmallFixed2$param[, 4], 20), trim=.2) ##  10.35295
save(resultsSSModSmallFixed2, file="SSModSmallFixedCC3000.RData")

ptm <- proc.time()
resultsSSModSmallFixed3 <- computeMLE(ssModel,paramNodesSS,
                                    method="fixed", paramInit=init,
                                    compiledFuns=compiledFunsSSmodel,
                                    stepsize=0.005,
                                    numMCMCSamples=numMCMCSamples,
                                    maxIter=300,
                                    boundary=boundary,trackEffSizeGrad=F,skipConvCheck=T)
timeSSModSmallFixed3 <- proc.time() - ptm
timeSSModSmallFixed3  ##17.716  
resultsSSModSmallFixed3$iter ## 300
mean(tail(resultsSSModSmallFixed3$param[, 1], 20), trim=.2)  ##0.4025138
mean(tail(resultsSSModSmallFixed3$param[, 2], 20), trim=.2) ## 5.932239
mean(tail(resultsSSModSmallFixed3$param[, 3], 20), trim=.2)  ##  5.777795
mean(tail(resultsSSModSmallFixed3$param[, 4], 20), trim=.2) ## 10.02273
save(resultsSSModSmallFixed3, file="SSModSmallFixed.RData")

ptm <- proc.time()
resultsSSModSmallFixed4 <- computeMLE(ssModel,paramNodesSS,
                                    method="fixed", paramInit=init,
                                    compiledFuns=compiledFunsSSmodel,
                                    stepsize=0.005,
                                    numMCMCSamples=numMCMCSamples,
                                    maxIter=300,
                                    boundary=boundary,trackEffSizeGrad=F,skipConvCheck=F)
timeSSModSmallFixed4 <- proc.time() - ptm
timeSSModSmallFixed4  ##17.698 
resultsSSModSmallFixed4$iter ## 300
mean(tail(resultsSSModSmallFixed4$param[, 1], 20), trim=.2)  ## 0.4045517
mean(tail(resultsSSModSmallFixed4$param[, 2], 20), trim=.2) ## 5.934522
mean(tail(resultsSSModSmallFixed4$param[, 3], 20), trim=.2)  ##  5.773506
mean(tail(resultsSSModSmallFixed4$param[, 4], 20), trim=.2) ## 10.02225
save(resultsSSModSmallFixed4, file="SSModSmallFixedCC.RData")
```

```{r}
# 3. Adadelta ----------------------------------------
ptm <- proc.time()
resultsSSModAdadelta <- computeMLE(ssModel, paramNodesSS,
                                  method="adadelta", paramInit=init,
                                  compiledFuns=compiledFunsSSmodel,
                                  numMCMCSamples=numMCMCSamples,
                                  maxIter=300,
                                  boundary=boundary,trackEffSizeGrad=F,skipConvCheck=T)
timeSSModAdadelta <- proc.time() - ptm
timeSSModAdadelta  ##  17.423 
resultsSSModAdadelta$iter ## 300
mean(tail(resultsSSModAdadelta$param[, 1], 20), trim=.2)  ##  0.5224348
mean(tail(resultsSSModAdadelta$param[, 2], 20), trim=.2)  ##4.203184
mean(tail(resultsSSModAdadelta$param[, 3], 20), trim=.2)  ## 6.277823
mean(tail(resultsSSModAdadelta$param[, 4], 20), trim=.2)  ## 12.17862
save(resultsSSModAdadelta, file="SSModAdadelta.RData")

ptm <- proc.time()
resultsSSModAdadelta2 <- computeMLE(ssModel, paramNodesSS,
                                  method="adadelta", paramInit=init,
                                  compiledFuns=compiledFunsSSmodel,
                                  numMCMCSamples=numMCMCSamples,
                                  maxIter=300,
                                  boundary=boundary,trackEffSizeGrad=F,skipConvCheck=F)
timeSSModAdadelta2 <- proc.time() - ptm
timeSSModAdadelta2  ## 18.419 
resultsSSModAdadelta2$iter ## 300
mean(tail(resultsSSModAdadelta2$param[, 1], 20), trim=.2)  ##  0.4909133
mean(tail(resultsSSModAdadelta2$param[, 2], 20), trim=.2)  ##4.26288
mean(tail(resultsSSModAdadelta2$param[, 3], 20), trim=.2)  ## 6.301222
mean(tail(resultsSSModAdadelta2$param[, 4], 20), trim=.2)  ##12.1951
save(resultsSSModAdadelta2, file="SSModAdadeltaCC.RData")

```

```{r}

# 4. Adam ----------------------------------------
ptm <- proc.time()
resultsSSModAdam <- computeMLE(ssModel, paramNodesSS,
                              method="adam", paramInit=init,
                              compiledFuns=compiledFunsSSmodel,
                              numMCMCSamples=numMCMCSamples,
                            maxIter=300,
                              #maxIter=500,
                              boundary=boundary,trackEffSizeGrad=F,skipConvCheck=T)
timeSSModAdam <- proc.time() - ptm
timeSSModAdam  ## 17.596 
resultsSSModAdam$iter ## 300
mean(tail(resultsSSModAdam$param[, 1], 20), trim=.2)  ##0.4713427
mean(tail(resultsSSModAdam$param[, 2], 20), trim=.2)  ## 4.898543
mean(tail(resultsSSModAdam$param[, 3], 20), trim=.2)  ## 5.740359
mean(tail(resultsSSModAdam$param[, 4], 20), trim=.2) ## 17.39691
save(resultsSSModAdam, file="SSModAdam.RData")

ptm <- proc.time()
resultsSSModAdam2 <- computeMLE(ssModel, paramNodesSS,
                              method="adam", paramInit=init,
                              compiledFuns=compiledFunsSSmodel,
                              numMCMCSamples=numMCMCSamples,
                            maxIter=300,
                              #maxIter=500,
                              boundary=boundary,trackEffSizeGrad=F,skipConvCheck=F)
timeSSModAdam2 <- proc.time() - ptm
timeSSModAdam2  ## 17.297 
resultsSSModAdam2$iter ## 300
mean(tail(resultsSSModAdam2$param[, 1], 20), trim=.2)  ##  0.4824108
mean(tail(resultsSSModAdam2$param[, 2], 20), trim=.2)  ## 4.842859
mean(tail(resultsSSModAdam2$param[, 3], 20), trim=.2)  ## 5.756251
mean(tail(resultsSSModAdam2$param[, 4], 20), trim=.2) ## 16.47873
save(resultsSSModAdam2, file="SSModAdamCC.RData")

```

```{r}
# 5. Newton-Raphson ----------------------------------------
ptm <- proc.time()
resultsSSModNR <- computeMLE(ssModel, paramNodes=paramNodesSS,
                            method="NR", paramInit=init,
                            compiledFuns=compiledFunsSSmodel,
                            numMCMCSamples=numMCMCSamples,
                            tol=1e-20,
                            maxIter=300,
                            boundary=boundary,trackEffSizeGrad=F,skipConvCheck=T)
timeSSModNR <- proc.time() - ptm
timeSSModNR  ## 37.230 
resultsSSModNR$iter # 300
mean(tail(resultsSSModNR$param[, 1], 20), trim=.2) ## -0.7385711
mean(tail(resultsSSModNR$param[, 2], 20), trim=.2)  ## 100
mean(tail(resultsSSModNR$param[, 3], 20), trim=.2) ##  100
mean(tail(resultsSSModNR$param[, 4], 20), trim=.2)  ##  2631.368
save(resultsSSModNR, file="SSModNR.RData")

ptm <- proc.time()
resultsSSModNR2 <- computeMLE(ssModel, paramNodes=paramNodesSS,
                            method="NR", paramInit=init,
                            compiledFuns=compiledFunsSSmodel,
                            numMCMCSamples=numMCMCSamples,
                            tol=1e-20,
                            maxIter=300,
                            boundary=boundary,trackEffSizeGrad=F,skipConvCheck=F)
timeSSModNR2 <- proc.time() - ptm
timeSSModNR2  ##37.632 
resultsSSModNR2$iter # 300
mean(tail(resultsSSModNR2$param[, 1], 20), trim=.2) ## 0.06195464
mean(tail(resultsSSModNR2$param[, 2], 20), trim=.2)  ##  96.72832
mean(tail(resultsSSModNR2$param[, 3], 20), trim=.2) ##  100
mean(tail(resultsSSModNR2$param[, 4], 20), trim=.2)  ##  243.6588
save(resultsSSModNR2, file="SSModNRCC.RData")
```

```{r}
# 6. 1-D sampling ----------------------------------------
ptm <- proc.time()
resultsSSMod1D <- computeMLE(ssModel, paramNodesSS,
                            method="ga1D", paramInit=init,
                            compiledFuns=compiledFunsSSmodel,
                            numMCMCSamples=300, numMCMCSamples1D=300, 
                            maxIter=300,skipConvCheck=T)
timeSSMod1D <- proc.time() - ptm
timeSSMod1D  ##  81.062 
resultsSSMod1D$iter ## 300
mean(tail(resultsSSMod1D$param[, 1], 20), trim=.2)  ## 0.5128038
mean(tail(resultsSSMod1D$param[, 2], 20), trim=.2)   ## 4.515337
mean(tail(resultsSSMod1D$param[, 3], 20), trim=.2) ## 6.117298
mean(tail(resultsSSMod1D$param[, 4], 20), trim=.2)  ##  10.16848
save(resultsSSMod1D, file="SSMod1D.RData")

ptm <- proc.time()
resultsSSMod1D2 <- computeMLE(ssModel, paramNodesSS,
                            method="ga1D", paramInit=init,
                            compiledFuns=compiledFunsSSmodel,
                            numMCMCSamples=300, numMCMCSamples1D=300, 
                            maxIter=300,skipConvCheck=F)
timeSSMod1D2 <- proc.time() - ptm
timeSSMod1D2  ##  80.131 
resultsSSMod1D2$iter ## 300
mean(tail(resultsSSMod1D2$param[, 1], 20), trim=.2)  ## 0.4779758
mean(tail(resultsSSMod1D2$param[, 2], 20), trim=.2)   ##  4.999879
mean(tail(resultsSSMod1D2$param[, 3], 20), trim=.2) ## 5.632711
mean(tail(resultsSSMod1D2$param[, 4], 20), trim=.2)  ##  10.21451
save(resultsSSMod1D2, file="SSMod1DCC.RData")

```


```{r}
# 7. Hybrid
# Run 10 iterations of 1D, and then run Adam.
ptm <- proc.time()
resultsSSMod1DFirst <- computeMLE(ssModel, paramNodesSS,
                                 method="ga1D", paramInit=init,
                                 compiledFuns=compiledFunsSSmodel,
                                 numMCMCSamples=numMCMCSamples, 
                                 numMCMCSamples1D=300, 
                                 maxIter=10)
resultsSSModAdamSecond <- computeMLE(ssModel, paramNodesSS,
                                    method="adam", 
                                    paramInit=tail(resultsSSMod1DFirst$param, 1),
                                    compiledFuns=compiledFunsSSmodel,
                                    numMCMCSamples=numMCMCSamples,
                                    maxIter=300,
                                    boundary=boundary)
timeSSModHybrid <- proc.time() - ptm
timeSSModHybrid  ##  23.544 
resultsSSModAdamSecond$iter ## 300
mean(tail(resultsSSModAdamSecond$param[, 1], 20), trim=.2)   ## 0.445668
mean(tail(resultsSSModAdamSecond$param[, 2], 20), trim=.2)   ##  7.243499
mean(tail(resultsSSModAdamSecond$param[, 3], 20), trim=.2)   ## 3.187646
mean(tail(resultsSSModAdamSecond$param[, 4], 20), trim=.2)  ## -3.627633

```

```{r}
# MCEM -----------------------------
#source("MCEM_with_output.R")
SSMod2 <- ssModel$newModel()

latentNodes <- SSMod2$getNodeNames(latentOnly=TRUE, stochOnly=TRUE)


#box <- list(list(c('sigPN', 'sigOE'), c(1e-04, 100)),list(c("rho"),c(-0.9999, 0.9999)),list(c("x0"),c(-Inf,Inf)))
SSModMCEM <- buildMCEM(model=SSMod2, latentNodes=latentNodes)
ptm <- proc.time()
resultsSSModMCEM <- SSModMCEM$run(initM = 1000)
timeSSModMCEM <- proc.time() - ptm
timeSSModMCEM  ## 228.136 

resultsSSModMCEM
##  rho         sigPN         sigOE            x0 
#-1.495863e-03  5.569224e+00  5.749870e+00 -6.244157e+03 

# |-------------------------------------------------------|
# Iteration Number: 1.
# Current number of MCMC iterations: 1000.
# Parameter Estimates: 
#         rho       sigPN       sigOE          x0 
#   -0.127162   47.180414   47.704135 -104.694772 
# Convergence Criterion: 1.001.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Iteration Number: 2.
# Current number of MCMC iterations: 1000.
# Parameter Estimates: 
#           rho         sigPN         sigOE            x0 
#   -0.06290311   33.68225322   33.72246390 -104.69796670 
# Convergence Criterion: 9.971094.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Iteration Number: 3.
# Current number of MCMC iterations: 1000.
# Parameter Estimates: 
#           rho         sigPN         sigOE            x0 
#   -0.03378318   24.13966885   24.18091704 -104.69770111 
# Convergence Criterion: 9.50482.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Iteration Number: 4.
# Current number of MCMC iterations: 1000.
# Parameter Estimates: 
#           rho         sigPN         sigOE            x0 
#   -0.02227477   17.54461851   17.56837383 -104.70646806 
# Convergence Criterion: 8.803084.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Iteration Number: 5.
# Current number of MCMC iterations: 1000.
# Parameter Estimates: 
#           rho         sigPN         sigOE            x0 
#   -0.02617753   13.03858088   13.05245638 -104.70659361 
# Convergence Criterion: 7.671806.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Iteration Number: 6.
# Current number of MCMC iterations: 1000.
# Parameter Estimates: 
#           rho         sigPN         sigOE            x0 
#   -0.02372251   10.02303871   10.03553847 -104.70874529 
# Convergence Criterion: 6.132552.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Iteration Number: 7.
# Current number of MCMC iterations: 1000.
# Parameter Estimates: 
#           rho         sigPN         sigOE            x0 
#   -0.01520584    8.17336909    8.16904252 -104.71038235 
# Convergence Criterion: 3.95682.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Iteration Number: 8.
# Current number of MCMC iterations: 1000.
# Parameter Estimates: 
#           rho         sigPN         sigOE            x0 
#   -0.01205311    7.03750983    7.02886744 -104.71078036 
# Convergence Criterion: 2.185406.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Iteration Number: 9.
# Current number of MCMC iterations: 1000.
# Parameter Estimates: 
#           rho         sigPN         sigOE            x0 
#   -0.01577364    6.39673037    6.42540070 -104.71143473 
# Convergence Criterion: 0.9004176.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Iteration Number: 10.
# Current number of MCMC iterations: 1000.
# Parameter Estimates: 
#           rho         sigPN         sigOE            x0 
#   -0.01214742    6.03523061    6.11046705 -104.71172734 
# Convergence Criterion: 0.3510875.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Iteration Number: 11.
# Current number of MCMC iterations: 1000.
# Parameter Estimates: 
#           rho         sigPN         sigOE            x0 
#   -0.01261737    5.85955936    5.90291656 -104.71238347 
# Convergence Criterion: 0.1287737.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Iteration Number: 12.
# Current number of MCMC iterations: 1000.
# Parameter Estimates: 
#           rho         sigPN         sigOE            x0 
#   -0.01500167    5.77091535    5.81082812 -104.71284611 
# Convergence Criterion: 0.04137495.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Iteration Number: 13.
# Current number of MCMC iterations: 1000.
# Parameter Estimates: 
#           rho         sigPN         sigOE            x0 
#   -0.01519294    5.70423134    5.75699745 -104.71317290 
# Convergence Criterion: 0.02101827.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Iteration Number: 14.
# Current number of MCMC iterations: 1000.
# Parameter Estimates: 
#           rho         sigPN         sigOE            x0 
#   -0.01536459    5.68816135    5.72905640 -104.71355742 
# Convergence Criterion: 0.004767939.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Monte Carlo error too big: increasing MCMC sample size.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Iteration Number: 15.
# Current number of MCMC iterations: 1250.
# Parameter Estimates: 
#           rho         sigPN         sigOE            x0 
# -8.690425e-04  5.665175e+00  5.722215e+00 -6.244157e+03 
# Convergence Criterion: 0.2675816.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Iteration Number: 16.
# Current number of MCMC iterations: 1250.
# Parameter Estimates: 
#           rho         sigPN         sigOE            x0 
# -1.191083e-03  5.638501e+00  5.723849e+00 -6.244157e+03 
# Convergence Criterion: 0.05488576.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Iteration Number: 17.
# Current number of MCMC iterations: 1250.
# Parameter Estimates: 
#           rho         sigPN         sigOE            x0 
# -1.333801e-03  5.618384e+00  5.736279e+00 -6.244157e+03 
# Convergence Criterion: 0.01591685.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Iteration Number: 18.
# Current number of MCMC iterations: 1250.
# Parameter Estimates: 
#           rho         sigPN         sigOE            x0 
# -1.426603e-03  5.596344e+00  5.741373e+00 -6.244157e+03 
# Convergence Criterion: 0.009514553.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Monte Carlo error too big: increasing MCMC sample size.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Monte Carlo error too big: increasing MCMC sample size.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Monte Carlo error too big: increasing MCMC sample size.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Iteration Number: 19.
# Current number of MCMC iterations: 3032.
# Parameter Estimates: 
#           rho         sigPN         sigOE            x0 
# -1.455149e-03  5.586101e+00  5.740618e+00 -6.244157e+03 
# Convergence Criterion: 0.001702723.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Iteration Number: 20.
# Current number of MCMC iterations: 3032.
# Parameter Estimates: 
#           rho         sigPN         sigOE            x0 
# -1.467893e-03  5.572951e+00  5.733975e+00 -6.244157e+03 
# Convergence Criterion: 0.001632772.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Monte Carlo error too big: increasing MCMC sample size.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Iteration Number: 21.
# Current number of MCMC iterations: 4298.
# Parameter Estimates: 
#           rho         sigPN         sigOE            x0 
# -1.493678e-03  5.571000e+00  5.741859e+00 -6.244157e+03 
# Convergence Criterion: 0.001229067.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Monte Carlo error too big: increasing MCMC sample size.
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# Iteration Number: 22.
# Current number of MCMC iterations: 6197.
# Parameter Estimates: 
#           rho         sigPN         sigOE            x0 
# -1.495863e-03  5.569224e+00  5.749870e+00 -6.244157e+03 
# Convergence Criterion: 0.0008831236.

# Save outputs ------------------------
save(resultsSSModMCEM, file="MCEM_SSMod.RData")
```

```{r}
timeInfo <- cbind(c(timeSSModFixed, timeSSModSmallFixed,
                    timeSSModAdadelta, timeSSModAdam,
                    timeSSModNR, timeSSMod1D, timeSSModMCEM),
                  c("fixed", "smallFixed", "adadelta", "adam",
                    "NR", "1D", "mcem"))

write.csv(timeInfo, "timeSSMod.csv", row.names=F)

```