---
title: "stochVolatilityExample"
author: "Sara Stoudt"
date: "September 16, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("MCMCmaxlik")
```

```{r}
phi=.2
mu=10
sigmaEta=3
h=rep(0,50)
etat=rnorm(50,0,sd=sigmaEta)
ut=rnorm(50)
y=rep(ut[1]*exp(0/2),50)
for(i in 2:50){
  h[i]=mu+phi*(h[i-1]-mu)+etat[i]
  y[i]=ut[i]*exp(h[i]/2)
}

write.csv(cbind(ut,h,y),"stocVolModData.csv") 
```

```{r}
svCode <- nimbleCode({
 ut[1] ~ dnorm(0,1)
 etat[1] ~ dnorm(0,sd=sigmaEta)
  #h[1] <- 0
  y[1] <- ut[1]*exp(h[1]/2)
  for (i in 2:TT) {
    h[i] <- mu+phi*(h[i-1]-mu)+etat[i]
    y[i] <- ut[i]*exp(h[i]/2)
     ut[i] ~ dnorm(0,1)
      etat[i] ~ dnorm(0,sd=sigmaEta)
  }
  phi ~dunif(-.999,0.999)
  mu ~ dnorm(0, sd = 1000)
  sigmaEta~dunif(0, 1000)
})

Consts <- list(TT = 50)

data <- list(
  h=h,
  y=y
)

inits <- list(phi=.5,mu=10,sigmaEta=5,ut=rep(2,50))


## build the model object
svModel <- nimbleModel(svCode, constants = Consts,data=data,inits=inits)



## put values in the top-level parameters
# svModel$phi <- 0.5
# svModel$mu <- 2.0
# sigmaEta <- 2.0
# 
# ## calculate any dependencies that may be needed to simulate states and data
# svModel$calculate(svModel$getDependencies( c('phi','mu','sigmaEta'), determOnly = TRUE))
# 
# 
# ## use the model to simulate states and data
# set.seed(12345)
# svModel$simulate( svModel$getDependencies(c('h','y')))
# ## Look at what we got:
# svModel$h
# svModel$y
# svModel$setData('y')
## this wasn't working

paramNodesSV <- svModel$getNodeNames(topOnly=T)
paramNodesSV=paramNodesSV[-c(1:50)] ## remove the ut's
CsvModel <- compileNimble(svModel)
```

```{r compile}
compiledFunsSVmodel <- buildMCMCmaxlik(svModel, paramNodesSV)

```


# Testing Algorithms

```{r}
# 1. Fixed step size ----------------------------------------
# Compile the necesvary functions.

# need to make sure these are in the right order
init <- c(0.75,20,1)
boundary <- list(c(-.9999,0.9999),c(-1000,1000),c(0,1000))
numMCMCSamples <- 300

ptm <- proc.time()
resultsSVModFixed <- computeMLE(svModel, paramNodesSV,
                               method="fixed", paramInit=init,
                               compiledFuns=compiledFunsSVmodel,
                               stepsize=0.05,
                               numMCMCSamples=numMCMCSamples,
                               maxIter=300,
                               boundary=boundary)
timesSVModFixed <- proc.time() - ptm
timesSVModFixed 
#warning: problem initializing stochastic node, logProb less than -1e12
#|-------------|-------------|-------------|-------------|
#|-------------------------------------------------------|
resultsSVModFixed$iter
mean(tail(resultsSVModFixed$param[, 1], 20), trim=.2)  ##  
mean(tail(resultsSVModFixed$param[, 2], 20), trim=.2)  ## 
mean(tail(resultsSVModFixed$param[, 3], 20), trim=.2)  ## 

save(resultsSVModFixed, file="svModFixed.RData")
```

```{r}
# 2. Small fixed step size ----------------------------------------
ptm <- proc.time()
resultsSVModSmallFixed <- computeMLE(svModel, paramNodesSV,
                                    method="fixed", paramInit=init,
                                    compiledFuns=compiledFunsSVmodel,
                                    stepsize=0.005,
                                    numMCMCSamples=numMCMCSamples,
                                    maxIter=3000,
                                    boundary=boundary)
timesSVModSmallFixed <- proc.time() - ptm ## 233.045 
timesSVModSmallFixed   ## 811.290 
resultsSVModSmallFixed$iter ## 3000
mean(tail(resultsSVModSmallFixed$param[, 1], 20), trim=.2)  ## 0.75
mean(tail(resultsSVModSmallFixed$param[, 2], 20), trim=.2) ##  20.00034
mean(tail(resultsSVModSmallFixed$param[, 3], 20), trim=.2)  ##  106.6361

save(resultsSVModSmallFixed, file="svModSmallFixed.RData")
```

```{r}
# 3. Adadelta ----------------------------------------
ptm <- proc.time()
resultsSVModAdadelta <- computeMLE(svModel, paramNodesSV,
                                  method="adadelta", paramInit=init,
                                  compiledFuns=compiledFunsSVmodel,
                                  numMCMCSamples=numMCMCSamples,
                                  maxIter=300,
                                  boundary=boundary)
timesSVModAdadelta <- proc.time() - ptm
timesSVModAdadelta  ## 20.699 
#300
mean(tail(resultsSVModAdadelta$param[, 1], 20), trim=.2)  ## 0.75
mean(tail(resultsSVModAdadelta$param[, 2], 20), trim=.2)  ## 20.04093
mean(tail(resultsSVModAdadelta$param[, 3], 20), trim=.2)  ## 8.19414
save(resultsSVModAdadelta, file="svModAdadelta.RData")

```

```{r}

# 4. Adam ----------------------------------------
ptm <- proc.time()
resultsSVModAdam <- computeMLE(svModel, paramNodesSV,
                              method="adam", paramInit=init,
                              compiledFuns=compiledFunsSVmodel,
                              numMCMCSamples=numMCMCSamples,
                              maxIter=300,
                              boundary=boundary)
timesSVModAdam <- proc.time() - ptm
timesSVModAdam  ## 26.909 
## 300
mean(tail(resultsSVModAdam$param[, 1], 20), trim=.2)  ##  0.75
mean(tail(resultsSVModAdam$param[, 2], 20), trim=.2)  ##22.53195
mean(tail(resultsSVModAdam$param[, 3], 20), trim=.2)  ## 19.27253
save(resultsSVModAdam, file="svModAdam.RData")

```

```{r}
# 5. Newton-Raphson ----------------------------------------
ptm <- proc.time()
resultsSVModNR <- computeMLE(svModel, paramNodes=paramNodesSV,
                            method="NR", paramInit=init,
                            compiledFuns=compiledFunsSVmodel,
                            numMCMCSamples=numMCMCSamples,
                            tol=1e-20,
                            maxIter=300,
                            boundary=boundary)
timesSVModNR <- proc.time() - ptm
timesSVModNR 
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# [1]  0.000000e+00 -1.756226e-04 -1.005698e+01
# Error in if (thetaNew[i] < boundary[[i]][1]) { : 
#   missing value where TRUE/FALSE needed

mean(resultsSVModNR$param[201:300,1], trim=.2)
mean(resultsSVModNR$param[201:300,2], trim=.2) 
mean(resultsSVModNR$param[201:300,3], trim=.2)
mean(resultsSVModNR$param[201:300,4], trim=.2)
save(resultsSVModNR, file="svModNR.RData")
```

```{r}
# 6. 1-D sampling ----------------------------------------
ptm <- proc.time()
resultsSVMod1D <- computeMLE(svModel, paramNodesSV,
                            method="ga1D", paramInit=init,
                            compiledFuns=compiledFunsSVmodel,
                            numMCMCSamples=300, numMCMCSamples1D=300, 
                            maxIter=300)
timesSVMod1D <- proc.time() - ptm
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
# warning: problem initializing stochastic node, logProb less than -1e12
# |-------------|-------------|-------------|-------------|
# |-------------------------------------------------------|
timesSVMod1D  ## 1.884 
mean(tail(resultsSVMod1D$param[, 1], 20), trim=.2)  ## 0.1099437
mean(tail(resultsSVMod1D$param[, 2], 20), trim=.2)  ##  0.999
mean(tail(resultsSVMod1D$param[, 3], 20), trim=.2)  ## 1.077608
save(resultsSVMod1D, file="svMod1D.RData")

```


```{r}
# 7. Hybrid
# Run 10 iterations of 1D, and then run Adam.
ptm <- proc.time()
resultsSVMod1DFirst <- computeMLE(svModel, paramNodesSV,
                                 method="ga1D", paramInit=init,
                                 compiledFuns=compiledFunsSVmodel,
                                 numMCMCSamples=numMCMCSamples, 
                                 numMCMCSamples1D=300, 
                                 maxIter=10)
resultsSVModAdamSecond <- computeMLE(svModel, paramNodesSV,
                                    method="adam", 
                                    paramInit=tail(resultsSVMod1DFirst$param, 1),
                                    compiledFuns=compiledFunsSVmodel,
                                    numMCMCSamples=numMCMCSamples,
                                    maxIter=300,
                                    boundary=boundary)
timesSVModHybrid <- proc.time() - ptm
timesSVModHybrid ##  9.153 

mean(tail(resultsSVModAdamSecond$param[, 1], 20), trim=.2)  ## -9.993417
mean(tail(resultsSVModAdamSecond$param[, 2], 20), trim=.2)  ##  0.999
mean(tail(resultsSVModAdamSecond$param[, 3], 20), trim=.2)  ## -1.550725
mean(tail(resultsSVModAdamSecond$param[, 4], 20), trim=.2)  ## 6.777809

```

```{r}
# MCEM -----------------------------
#source("MCEM_with_output.R")
svMod2 <- svModel$newModel()

box <- list(list(c('sigmaEta'), c(0, 1000)),list(c("phi"),c(-0.9999, 0.9999)),list(c("mu"),c(-Inf,Inf)))
svModMCEM <- buildMCEM(model=svMod2, latentNodes=list(paramNodesSV),
                      boxConstraints=box)
# NAs introduced by coercionUser-specified lower bound for phi is below lower bound detected by NIMBLE.  User-specified upper bound for phi is above upper bound detected by NIMBLE.  Error in buildMCEM(model = svMod2, latentNodes = list(paramNodesSV), boxConstraints = box) : 
#   no latentNodes
svModel$getNodeNames(latentOnly=T)

ptm <- proc.time()
resultsSVModMCEM <- svModMCEM$run(initM = 1000) 
timesSVModMCEM <- proc.time() - ptm
timesSVModMCEM 

# Save outputs ------------------------
save(resultsSVModMCEM, file="MCEM_svMod.RData")
```

```{r}
timeInfo <- cbind(c(timesSVModFixed, timesSVModSmallFixed,
                    timesSVModAdadelta, timesSVModAdam,
                    timesSVModNR, timesSVMod1D, timesSVModMCEM),
                  c("fixed", "smallFixed", "adadelta", "adam",
                    "NR", "1D", "mcem"))

write.csv(timeInfo, "timesSVMod.csv", row.names=F)

```