#' Compute the MLE using Adagrad.
#'
#' This function computes the MLE of the top-level parameters of a
#' hierarchical model with latent variables using Adam.
#' @param model a nimble model object
#' @param paramNodes a character vector indicating the top-level parameters
#' @param compiledFuns a list of compiled function, generated by buildMCMCmaxlik()
#' @param paramInit the initial starting point
#' @param boundary the range of the top-level parameters, 
#' default to using getBound() 
#' @param postMode a boolean indicating whether to include prior in the calculation
#' @param trackEffSizeGrad a boolean indicating whether effective size of the MCMC
#' samples is checked
#' @param maxIter maximum number of iterations
#' @param numMCMCSamples MCMC sample size for gradient approximation
#' @param delta finite element differences
#' @param burninFrac the fraction of burn-in samples for gradient approximation
#' @param stepsize the step size
#' @param eps epsilon
#' @param blockSize the size of blocks for convergence checking
#' @param runsThreshold the cutoff for acceptable number of runs within a block
#' of iterates, default to one-fifth of the block size
#' @param pValsThreshold the cutoff of p-value threshold for comparing
#' averages between two blocks of iterates
#' @keywords MLE
#' @export
#' @examples
#' adagradMLE()

adagradMLE <- function(model, paramNodes, compiledFuns, paramInit, 
                       boundary=NULL,
                       postMode = F, maxIter = 100,
                       burninFrac = 0.5,
                       numMCMCSamples = 10000, 
                       eta=0.01, delta = 1e-04, eps = 1e-2,
                       tol = 1e-04,
                       skipConvCheck=FALSE,
                       runUntilMaxIter=TRUE,
                       blockSize = 20, runsThreshold = floor(blockSize / 5),
                       pValThreshold = 0.3) {
  
  ptm <- proc.time()
  
  # Determine the boundary conditions.
  if (is.null(boundary)) {
    boundary=vector('list',length(paramNodes))
    for(i in 1:length(paramNodes)){
      boundary[[i]] <-
        c(getBound(model,paramNodes[i],'lower'),
          getBound(model,paramNodes[i],'upper'))
    }
  }
  
  thetaCur <- paramInit
  thetaNew <- paramInit
  iter <- 1
  thr <- Inf
  paramMatrix <- matrix(nrow = maxIter, ncol = length(paramInit))
  accumGrad <- numeric(length(paramInit))
  paramMatrix[1, ] <- paramInit
  while (iter < maxIter & thr > tol) {
    compiledFuns$setParams$run(paramMatrix[iter, ])
    compiledFuns$MCMC$run(numMCMCSamples)
    compiledFuns$computeGrad$run(delta, postMode, burninFrac)
    gradCurr <- compiledFuns$computeGrad$grad
    accumGrad <- accumGrad + (gradCurr ^ 2)
    RMSGrad <- sqrt(accumGrad + eps)
    updateCurr <- eta / RMSGrad * gradCurr
    thetaNew <- paramMatrix[iter, ] + updateCurr
    # Check boundaries. (Projected)
    if (any(is.na(thetaNew))) {
      break
    }
    for (i in 1:length(paramNodes)) {
      if (thetaNew[i] < boundary[[i]][1]) {
        thetaNew[i] = boundary[[i]][1]
      }
      else if (thetaNew[i] > boundary[[i]][2]) {
        thetaNew[i] = boundary[[i]][2]
      }
      else {
        thetaNew[i] = thetaNew[i]
      }
    }
    paramMatrix[iter + 1, ] <- thetaNew
    thr <- sum((gradCurr)^2)
    thetaCur <- thetaNew
    compiledFuns$setLatent$run(tail(as.matrix(compiledFuns$MCMC$mvSamples), 1))
    
    iter <- iter + 1
    
    # Convergence test
    if (!converge & iter > 2 * blockSize) {
      # 1. Check oscillating behaviors.
      runsResults <- checkRuns(paramMatrix[(iter - blockSize):(iter - 1), ],
                               runsThreshold)
      if (runsResults$pass) {
        # 2. Check whether the average stays constant.
        blockResults <- checkBlocks(
          paramMatrix[(iter - 2 * blockSize):(iter - blockSize - 1), ],
          paramMatrix[(iter - blockSize):(iter - 1), ],
          pValThreshold)
        if (blockResults$pass) {
          convergence.time <- proc.time() - ptm
          convergence.iter <- iter - 1
          converge <- T
        }
        if (!runUntilMaxIter) break
      }
    }
  }
  
  if (!skipConvCheck & iter > 2 * blockSize) {
    cat("*** Convergence diagnostics ***\n")
    if (converge) {
      cat(paste0("Converged at Iteration ", convergence.iter, "\n")) 
    }
    cat(paste0("Number(s) of runs (block size = ", blockSize, "): ", 
               paste0(runsResults$numRuns, collapse=", "),
               "\n"))
    if (runsResults$pass) {
      cat(paste0("p-value from 2-sample t-test for block comparisons: ",
                 paste(round(blockResults$pVal, 3), collapse=", "),
                 "\n")) 
    }
    
    if (!converge) {
      cat("*** Warning: Non-convergence ***\n")
      cat("Use a different starting point or increase the MCMC sample size.\n")
    }
  }
  
  paramMatrix <- na.omit(paramMatrix)
  if (iter > 20) {
    MLE <- apply(tail(paramMatrix, 20), 2, mean, trim=.2)
  } else {
    MLE <- tail(paramMatrix, 1)[1,]
  }
  
  results <- list(param = paramMatrix,
                  MLE = MLE, 
                  execution.time=proc.time() - ptm,
                  execution.iter=iter - 1)
  if (trackEffSizeGrad) {
    results <- c(results, list(effSizesGrad = effSizesGrad))
  }
  if (!skipConvCheck & iter > 2 * blockSize & converge) {
    results <- c(results, 
                 list(convergence.time=convergence.time,
                      convergence.iter=convergence.iter))
  }
  return(results)
}