#' Compute the MLE using 1D sampling.
#'
#' This function computes the MLE of the top-level parameters of a
#' hierarchical model with latent variables using 1D sampling.
#' @param model a nimble model object
#' @param paramNodes a character vector indicating the top-level parameters
#' @param compiledFuns a list of compiled function, generated by 
#' buildMCMCmaxlik()
#' @param paramInit the initial starting point
#' @param postMode a boolean indicating whether to include prior in the 
#' calculation
#' @param maxIter maximum number of iterations
#' @param numMCMCSamples MCMC sample size for gradient approximation
#' @param numMCMCSamples1D MCMC sample size for 1D sampling
#' @param burninFrac the fraction of burn-in samples for gradient approximation
#' @param burninFrac1D the fraction of burn-in samples for 1D sampling
#' @param tol the tolerance
#' @param boundary the range of the top-level parameters, 
#' default to using getBound() 
#' @keywords MLE
#' @export

ga1DMLE <- function(model, paramNodes, compiledFuns, paramInit,
                    boundary=NULL,
                    postMode=F, maxIter=100,
                    numMCMCSamples=300, numMCMCSamples1D=300,
                    burninFrac=0.5, burninFrac1D=0.5,
                    kern="gaussian", bdwth="nrd0",
                    tol=1e-04,
                    trackEffSizeGrad=FALSE,
                    skipConvCheck=FALSE,
                    runUntilMaxIter=TRUE,
                    blockSize = 20, runsThreshold = floor(blockSize / 5),
                    pValThreshold = 0.3,
                    returnHess = F) {
  
  ptm <- proc.time()
  
  if(is.null(boundary)){
    boundary=vector('list',length(paramNodes))
    for(i in 1:length(paramNodes)){
      boundary[[i]] <-
        c(getBound(model,paramNodes[i],'lower'),
          getBound(model,paramNodes[i],'upper'))
    }
  }
  
  compiledFuns$decideIncludePrior$run(postMode)
  iter <- 1
  converge <- F
  thr <- Inf
  paramMatrix <- matrix(nrow=maxIter + 1, ncol=length(paramInit))
  effSizes <- numeric(length=maxIter)
  latentNodes <- model$getNodeNames(latentOnly=TRUE, stochOnly=TRUE)
  effSizesGrad <-matrix(nrow=maxIter, ncol=length(latentNodes))
  # gelmanStat <- numeric(length=maxIter)
  paramMatrix[1, ] <- paramInit
  
  while (iter <= maxIter & thr > tol) {
    compiledFuns$setParams$run(paramMatrix[iter, ])
    compiledFuns$MCMC$run(numMCMCSamples)
    
    samplesGrad <- as.matrix(compiledFuns$MCMC$mvSamples)
    samplesGrad <- 
      samplesGrad[(ceiling(burninFrac * numMCMCSamples) + 1):numMCMCSamples,]
    
    effSizesGrad[iter,] <- round(effectiveSize(samplesGrad), 1)
    
    compiledFuns$computeGradHess$run(postMode, burninFrac, gradient = TRUE, hessian = FALSE)
    
    compiledFuns$MCMC1D$run(numMCMCSamples1D)
    samples1D <- as.matrix(compiledFuns$MCMC1D$mvSamples)
    gradCurr <- compiledFuns$computeGradHess$grad
    samplesb <- (samples1D[, 1] - paramMatrix[iter, 1]) / gradCurr[1]
    ### burn in
    burn.in <- ceiling(burninFrac1D * numMCMCSamples1D)
    samplesb <- samplesb[(burn.in+1):numMCMCSamples1D]
    effSizes[iter + 1] <- effectiveSize(samplesb)
    # account for dependence of samples
    stepsize <- getKernelMode(samplesb,
                              adjust=(numMCMCSamples1D / 
                                        (effSizes[iter] + 1))^(1/5),
                              kern=kern, bdwth=bdwth)
    
    thetaCurr <- paramMatrix[iter, ] + stepsize * gradCurr
    # Check boundaries. (Projected)
    
    for (i in 1:length(paramNodes)) {
      
      if (thetaCurr[i] < boundary[[i]][1]) {
        thetaCurr[i] <- boundary[[i]][1]
      }
      else if (thetaCurr[i] > boundary[[i]][2]) {
        thetaCurr[i] <- boundary[[i]][2]
      }
      else {
        thetaCurr[i] <- thetaCurr[i]
      }
    }
    
    paramMatrix[iter + 1, ] <- thetaCurr
    thr <- sum((gradCurr)^2)
    
    df <- data.frame(t(thetaCurr))
    names(df) <- paramNodes
    cat(paste0("Iteration Number: ", iter, ".\n",
               "Parameter Estimates:\n"))
    print(df, row.names=FALSE)
    cat(paste0("Effective Sample Size for gradient (raw, min): ", 
               min(effSizesGrad[iter, ]), 
               "\n"))
    cat(paste0("Effective Sample Size for 1D sampling: ", 
               effSizes[iter], "\n"))
    
    iter <- iter + 1
    
    # Convergence test
    if (!converge & iter > 2 * blockSize) {
      # 1. Check oscillating behaviors.
      runsResults <- checkRuns(paramMatrix[(iter - blockSize):(iter - 1), ],
                               runsThreshold)
      if (runsResults$pass) {
        # 2. Check whether the average stays constant.
        blockResults <- checkBlocks(
          paramMatrix[(iter - 2 * blockSize):(iter - blockSize - 1), ],
          paramMatrix[(iter - blockSize):(iter - 1), ],
          pValThreshold)
        if (blockResults$pass) {
          convergence.time <- proc.time() - ptm
          convergence.iter <- iter - 1
          converge <- T
          if (!runUntilMaxIter) break
        }
      }
    }
  }
  
  if (!skipConvCheck & iter > 2 * blockSize) {
    cat("*** Convergence diagnostics ***\n")
    if (converge) {
      cat(paste0("Converged at Iteration ", convergence.iter, "\n")) 
    }
    cat(paste0("Number(s) of runs (block size = ", blockSize, "): ", 
               paste0(runsResults$numRuns, collapse=", "),
               "\n"))
    if (runsResults$pass) {
      cat(paste0("p-value from 2-sample t-test for block comparisons: ",
                 paste(round(blockResults$pVal, 3), collapse=", "),
                 "\n")) 
    }
    
    if (!converge) {
      cat("*** Warning: Non-convergence ***\n")
      cat("Use a different starting point or increase the MCMC sample size.\n")
    }
  }
  
  paramMatrix <- na.omit(paramMatrix)
  if (iter > 20) {
    if (converge) {
      MLE <- apply(paramMatrix[(convergence.iter - 19):(convergence.iter), ], 2, mean, trim=.2)
    } else {
      MLE <- apply(tail(paramMatrix, 20), 2, mean, trim=.2)
    }
  } else {
    MLE <- tail(paramMatrix, 1)[1,]
  }
  
  results <- list(param = paramMatrix,
                  MLE = MLE, 
                  execution.time=proc.time() - ptm,
                  execution.iter=iter - 1)
  if (trackEffSizeGrad) {
    results <- c(results, list(effSizesGrad = effSizesGrad))
  }
  if (!skipConvCheck & iter > 2 * blockSize & converge) {
    results <- c(results, 
                 list(convergence.time=convergence.time,
                      convergence.iter=convergence.iter))
  }
  
  if (returnHess) {
    compiledFuns$computeGradHess$run(postMode, burninFrac, gradient = TRUE, hessian = TRUE)
    results <- c(results, list(hess=compiledFuns$computeGradHess$hess))
  }
  
  return(results)
}

getKernelMode <- function(samples, adjust=1, kern="gaussian", bdwth="nrd0") {
  d <- density(samples, bw=bdwth, kernel=kern, adjust=adjust)
  modeR <- d$x[which.max(d$y)]
  return(modeR)
}