#' Compute the MLE using Newton-Raphson.
#'
#' This function computes the MLE of the top-level parameters of a
#' hierarchical model with latent variables using Adadelta.
#' @param model a nimble model object
#' @param paramNodes a character vector indicating the top-level parameters
#' @param compiledFuns a list of compiled function, generated by buildMCMCmaxlik()
#' @param paramInit the initial starting point
#' @param boundary the range of the top-level parameters, 
#' default to using getBound() 
#' @param postMode a boolean indicating whether to include prior in the calculation
#' @param trackEffSizeGrad a boolean indicating whether effective size of the MCMC
#' samples is checked
#' @param maxIter maximum number of iterations
#' @param numMCMCSamples MCMC sample size for gradient approximation
#' @param delta finite element differences
#' @param burninFrac the fraction of burn-in samples for gradient approximation
#' @param stepsize the step size
#' @param eps epsilon
#' @param rho rho
#' @keywords MLE
#' @export
#' @examples
#' compileMLE()

NRMLE <- function(model, paramNodes, compiledFuns, paramInit, boundary=NULL,
                  postMode = F, trackEffSizeGrad = F, burninFrac = 0.5,
                  stepsize = 1, maxIter = 100, numMCMCSamples = 10000, 
                  delta = 1e-04, deltaHess=1e-02, tol = 1e-04,
                  blockSize = 20, runsThreshold = floor(blockSize / 5),
                  pValThreshold = 0.3) {
  
  if(is.null(boundary)){
    boundary=vector('list',length(paramNodes))
    for(i in 1:length(paramNodes)){
      boundary[[i]]=c(getBound(model,paramNodes[i],'lower'),
                      getBound(model,paramNodes[i],'upper'))
    }
  }
  
  thetaCur <- paramInit
  thetaNew <- paramInit
  iter <- 1
  thr <- Inf
  paramMatrix <- matrix(nrow = maxIter, ncol = length(paramInit))
  paramMatrix[1, ] <- paramInit
  
  while (iter < maxIter & thr > tol) {
    compiledFuns$setParams$run(paramMatrix[iter, ])
    compiledFuns$MCMC$run(numMCMCSamples)
    compiledFuns$computeGrad$run(delta, postMode, burninFrac)
    ## add warm up
    warmUp <- unname(as.matrix(compiledFuns$MCMC$mvSamples)[numMCMCSamples,])
    compiledFuns$setLatent$run(warmUp)
    gradCurr <- compiledFuns$computeGrad$grad
    print(gradCurr)
    approxHessian <- compiledFuns$computeHess$run(deltaHess, postMode, 
                                                  burninFrac)
    move <- solve(approxHessian, gradCurr)
    thetaNew <- paramMatrix[iter, ] - move
    s <- 1
    #print(thetaNew)
    while (checkOutOfRange(thetaNew, boundary)) {
      thetaNew <- paramMatrix[iter, ] - 0.8^s * move
      s <- s + 1
    }
    paramMatrix[iter + 1, ] <- thetaNew
    thr <- sum((gradCurr)^2)
    thetaCur <- thetaNew
    
    
    compiledFuns$setLatent$run(tail(as.matrix(compiledFuns$MCMC$mvSamples), 1))
    
    df <- data.frame(t(thetaCur))
    names(df) <- paramNodes
    cat(paste0("Iteration Number: ", iter, ".\n",
               "Parameter Estimates:\n"))
    print(df, row.names = FALSE)
    if (trackEffSizeGrad) {
      samplesGrad <- as.matrix(compiledFuns$MCMC$mvSamples)
      samplesGrad <- samplesGrad[(ceiling(burninFrac * numMCMCSamples) + 1):numMCMCSamples,]
      
      effSizesGrad[iter,] <- round(effectiveSize(samplesGrad), 1)
      cat(paste0("Effective Sample Size for gradient (raw, min): ", 
                 min(effSizesGrad[iter, ]), 
                 "\n")) 
    }
    # Convergence test
    if (iter > 2 * blockSize) {
      # 1. Check oscillating behaviors.
      runsResults <- checkRuns(paramMatrix[(iter - blockSize + 1):iter, ],
                               runsThreshold)
      if (runsResults$pass) {
        # 2. Check whether the average stays constant.
        blockResults <- checkBlocks(
          paramMatrix[(iter - 2 * blockSize + 1):(iter - blockSize), ],
          paramMatrix[(iter - blockSize + 1):iter, ],
          pValThreshold)
        if (blockResults$pass) {
          converge <- T
          break 
        }
      }
    }
    iter <- iter + 1
  }
  return(list(param = paramMatrix, iter = iter, hess = approxHessian))
}